[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Agromemnon"
version = "0.1.0"
description = "AgentCore Runtime Application using Strands SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aws-opentelemetry-distro ~= 0.18.0",
    "beautifulsoup4>=4.15.0",
    "bedrock-agentcore >= 1.9.1",
    "boto3>=1.43.96",
    "botocore[crt] >= 1.35.0",
    "mcp ~= 1.24.0",
    "rapidfuzz>=3.14.5",
    "requests>=2.34.2",
    "python-dotenv>=1.2.3",
    "strands-agents[gemini]>=1.15.0",
    "strands-agents-tools>=0.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
